### ISSUE TITLE
Add `path-to-regexp` for slug config

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/headless-static-site#8]
The headless static site needs to know how to extract IDs from URLs in order to map remote resources.

For example:
```
https://iiif.wellcomecollection.org/presentation/b30496974
```
This points to a IIIF Manifest, we want to be able to extract:
```
b30496974
```
And also optionally add a prefix, so that on the headless static site output it can be found at:
```
/manifests/wellcome-b30496974
```

In order to this currently we have a configuration object that must be specified by the user:
```yaml
slugs:
  wellcome-manifest:
    type: Manifest
    domain: iiif.wellcomecollection.org
    prefix: /presentation/
    addedPrefix: wellcome-
    examples:
      - https://iiif.wellcomecollection.org/presentation/b30496974
```

An alternative might be possible with [Path to regex](https://github.com/pillarjs/path-to-regexp) which is fast.

Here is the current store configuration, which references the slugs config above.
```yaml
  wellcomePaintings:
    type: iiif-remote
    url: https://iiif.wellcomecollection.org/presentation/collections/digitalcollections/digpaintings
    slugTemplates:
      - wellcome-manifest
      - wellcome-collection
```

With path-to-regex it could be:
```yaml
wellcomePaintings:
  type: iiif-remote
  url: https://iiif.wellcomecollection.org/presentation/collections/digitalcollections/digpaintings
  router:
    - from: https://iiif.wellcomecollection.org/presentation/collections/{*collectionPath}
      to: /collections/{*collectionPath}

    - from: https://iiif.wellcomecollection.org/presentation/{manifestId}
      to: /manifests/wellcome-{manifestId}
```

That would greatly simplify both the configuration and implementation.

With this configuration, if a static page was requested:
```
/manifests/wellcome-b30496974
```

The configuration provides enough information to match it against the router.
```diff
 from: https://iiif.wellcomecollection.org/presentation/{manifestId}
+to: /manifests/wellcome-{manifestId}
```

And then find the original manifest to fetch:

```
https://iiif.wellcomecollection.org/presentation/{manifestId}
```
Fetching:
```
https://iiif.wellcomecollection.org/presentation/b30496974
```

It would also still have the original path to fetch the `meta.json` and `indices.json` which are not hosted at Wellcome:
```
/iiif/manifests/wellcome-b30496974/meta.json
/iiif/manifests/wellcome-b30496974/indices.json
```
